jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout sources
      uses: actions/checkout@v1
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - continue-on-error: true
      env:
        AWS_ACCESS_KEY_ID: dummy
        AWS_REGION: us-east-1
        AWS_SECRET_ACCESS_KEY: dummy
        MODULE: ${{ matrix.module }}
      name: Build module ${{ matrix.module }}
      run: 'chmod 755 build-all.sh && ./build-all.sh $MODULE

        '
    - continue-on-error: true
      if: failure()
      name: Zip build reports
      run: zip -r reports.zip **/**/build/reports
    - continue-on-error: true
      if: failure()
      name: Upload build reports
      uses: actions/upload-artifact@v1
      with:
        name: reports
        path: reports.zip
    strategy:
      matrix:
        module:
        - module1
        - module2
        - module3
        - module4
        - module5
        - module6
        - module7
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
